config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'
  end 

  get 'static_pages/home'
  resources :articles

  root 'static_pages#home'

  get 'keywords/:id' => 'keywords#index', :as => 'show_keyword'

end

app/models/article.rb
class Article < ActiveRecord::Base
  before_create :downcase_tags

  belongs_to :user
  validates :user, :presence => true

  has_many :article_images, dependent: :destroy
  has_many :tags
  has_many :keywords, :through => :tags

  validates :title, presence: true, uniqueness: true
  validates :content, length: { minimum: 1, maximum: 10000,
          too_short: "%{count} characters is the minimum allowed",
          too_long: "%{count} characters is the maximum allowed" }

  accepts_nested_attributes_for :article_images
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :keywords

  def author
  	self.user.first_name + " " + self.user.last_name
  end


  def downcase_tags
      self.tags.each do |tag|
       
        tag.keyword.keyword = tag.keyword.keyword.downcase 
      end
  end

end

app/models/article_image.rb
class ArticleImage < ActiveRecord::Base
	mount_uploader :image, ImageUploader
    belongs_to :article, autosave: true
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_many :tags
	has_many :articles, :through => :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :article
	belongs_to :keyword, autosave: true

	accepts_nested_attributes_for :keyword,
                              :reject_if => :all_blank

	private
    	def autosave_associated_records_for_keyword
    		if new_keyword = Keyword.find_by_keyword(keyword.keyword)
    			self.keyword = new_keyword
            else
                keyword.save
                self.keyword = keyword
    		end
    	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :timeoutable, :trackable,
         :validatable
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    # return the path based on resource
    new_article_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		if(params[:id].present?)
			@articles = Article.where(user_id:params[:id])
		else
			@articles = Article.where(user_id:current_user.id)
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
		@article.tags.build
		@article.article_images.build
	end

	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			flash[:success] = "Article uploaded"
			redirect_to root_url
		else
			flash[:error] = @article.errors.full_messages.to_sentence
			render 'new'
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params)
			flash[:success] = "Article updated"
      		redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		Article.destroy(params[:id])
    	redirect_to root_url
	end

	private
		def article_params
			params.require(:article).permit(:title, :content, tags_attributes: [:id, keyword_attributes: [:keyword]], article_images_attributes: [:id, :image])
		end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
	def index
		@keyword = Keyword.find(params[:id])
		@articles = Article.includes(:tags).where( tags: {keyword: params[:id]})
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@articles = Article.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
  	
  	if @articles.size > 3
  		@carousel_articles = @articles.slice(0, 3)
  	else
		@carousel_articles = @articles
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def renderText(text)
		#Redcarpet::Render::HTML
		markdown = Redcarpet::Markdown.new(CustomMarkdown, no_intra_emphasis: true)
		return markdown.render(text).html_safe
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_article.html.erb
<article class="blog-post">
	<header>
		<h1 class="blog-post-title"><%= link_to article.title, article_path(article) %></h1>
		<%= render 'articles/editOptions', :article => article %>
		<small><time><%= article.created_at.strftime("%A #{article.created_at.day.ordinalize}, %B %Y")%></time> by <%= link_to article.author, articles_path(:id => article.user) %></small>
	</header>
	<%= renderText(article.content) %>
	<div class="panel-footer keywords">
		<% article.tags.each do |tag| %>
			<span class="label label-default"><%= link_to tag.keyword.keyword, show_keyword_path(tag.keyword) %></span>
		<% end %>
	</div>
</article>

app/views/articles/_article_image_fields.html.erb
<div class="form-group">
	<%= f.file_field :image %>
</div>

app/views/articles/_articleindex.html.erb
<article>
	<%= render 'articles/editOptions', :article => article %>
	<h2><%= link_to article.title, article_path(article) %></h2>
	<p><%= article.created_at.strftime("%A %e, %B %Y")%></p>
</article>

app/views/articles/_editOptions.html.erb
<% if user_signed_in? %>
	<ul class ="editOptions">
		<li><%= link_to 'Edit', edit_article_path(article)%> </li>
		<li><%= link_to 'Delete', article_path(article), method: 'delete' %></li>
	</ul>
<% end %>

app/views/articles/_tag_fields.html.erb
<div class="form-group">
	 <%= f.fields_for :keyword do |word| %>
     	<%= word.text_field :keyword %>
    <% end %>
</div>

app/views/articles/edit.html.erb
<fieldset>
	<legend>New Article</legend>
	<%= form_for(@article) do |f| %>
		<div class="form-group">
			<%= f.label :title %><br/>
			<%= f.text_field :title %><br/>
		</div>
		<div class="form-group">
			<%= f.label :content %><br/>
			<%= f.text_area :content %><br/>
		</div>
		<%= f.submit 'Post Article' %>
	<% end %>
</fieldset>

app/views/articles/index.html.erb
<% provide(:title, "Articles By #{@articles[0].author}") %>
<% @articles.each do |a| %>
	<%= render 'articles/articleindex', :article => a %>
<% end %>
<%= will_paginate @articles, page_links: false %>

app/views/articles/new.html.erb
<% provide(:title, "New Post") %>
<fieldset>
	<legend>New Article</legend>
	<%= form_for(@article, :html => { :multipart => true }) do |f| %>
		<div class="form-group">
			<%= f.label :title %><br/>
			<%= f.text_field :title %><br/>
		</div>
		<div class="form-group">
			<%= f.label :content %><br/>
			<button type ="button" class="btn" id="bold"><strong>B</strong></button>
			<button type ="button" class="btn" id="italic"><i>I</i></button>
			<button type ="button" class="btn" id="underline"><u>U</u></button>
			<button type ="button" class="btn" id="url">URL</button>
			<button type ="button" class="btn" id="blockquote">BQ</button>
     	 	<button type ="button" class="btn" id="ul">UL</button>
       		<button type ="button" class="btn" id="ol">OL</button><br/>
			<%= f.text_area :content %><br/>
		</div>
		<fieldset id="media">
			<legend>Media</legend>
			<ol>
				<%= f.fields_for :article_images do |image| %>
       				<%= link_to_add_association 'add media', f, :article_images, 'data-association-insertion-node' => "#media ol", 'data-association-insertion-method' => "append" %>
       			<% end %>
   			</ol>
		</fieldset>
		<fieldset id="tags">
			<legend>Tags</legend>
			<ol>
				<%= f.fields_for :tags do |tag| %>
    				<%= link_to_add_association 'add tag', f, :tags, 'data-association-insertion-node' => "#tags ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|tag| tag.build_keyword; tag} %>
      			<% end %>
      		</ol>
		</fieldset>
		<%= f.submit 'Post Article' %>
	<% end %>
</fieldset>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<%= render 'articles/article', :article => @article %>

app/views/keywords/index.html.erb
<% provide(:title, "Articles Featuring  #{@keyword.keyword}") %>
<h1><%= @keyword.keyword %></h1>
<% @articles.each do |a| %>
	<%= render 'articles/articleindex', :article => a %>
<% end %>

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
  <ol class="carousel-indicators">
   <% articles.each_with_index do |article, index| %>
      <% if index == 0 %>
        <li data-target="#myCarousel" data-slide-to=<%= index %> class="active"></li>
      <% else %>
        <li data-target="#myCarousel" data-slide-to=<%= index %> ></li>
      <% end %>  
    <% end %>
  </ol>

   <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% articles.each_with_index do |article, index| %>
      <% if index == 0 %>
        <%= render 'layouts/carousel_item', :article => article, :active => true %>
      <% else %>
        <%= render 'layouts/carousel_item', :article => article, :active => false %>
      <% end %>  
    <% end %>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_carousel_item.html.erb
<div class= "<%= active ? "item active" : "item" %>" >
	<% if article.article_images.size > 0 && article.article_images[0].image.header.file.exists? %>
		<%= link_to(image_tag(article.article_images[0].image.header.url), article) %>
	<% else %>
		<%= image_tag "placeholder.jpg" %>
	<% end %>
	<div class="carousel-caption">
		<h1><%= link_to article.title, article_path(article)  %></h1>
	</div>
</div>

app/views/layouts/_footer.html.erb
<hr id="bottomSeperator" />
<footer class="footer">
	<small class="text-muted">footer</small>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="jumbotron">
		<%= render 'layouts/nav' %>
		<h1><%= link_to 'Title', root_path %></h1>
	</div>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<ul class="nav navbar-nav">
		<li><a>1</a></li>
		<li><a>2</a></li>
		<li><a>3</a></li>
		<% if user_signed_in? %>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
             			 Account <b class="caret"></b>
            	</a>
				<ul class="dropdown-menu">
					<li><%= link_to 'New Article',new_article_path %></li>
					<li><%= link_to 'Published articles', articles_path%></li>
    				<li><%= link_to 'Edit Profile', edit_user_registration_path  %></li>
    				<li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
  				</ul>
  			</li>
		<% end %>
	</ul>
</nav>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | BootstrapTutorial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<%= render 'layouts/carousel', :articles => @carousel_articles %>
<% @articles.each do |a| %>
	<%= render 'articles/article', :article => a %>
<% end %>
<%= will_paginate @articles, page_links: false %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>